version: '3.8'
services:
  app:
    build: .
    entrypoint: /app/entrypoint.sh
    environment:
        - DYNACONF_DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/stripeljee_python
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stripeljee_python
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
    db_data:
