"""autro

Revision ID: cd3c0456e50a
Revises: 6cbc8207cc8b
Create Date: 2024-06-01 22:09:24.253314

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd3c0456e50a"
down_revision: Union[str, None] = "6cbc8207cc8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the enum type
    serietype = sa.Enum(
        "KIDS",
        "COMIC",
        "GRAPHIC_NOVEL",
        "MANGA",
        "CARTOON",
        "VOLWASSENEN",
        "ALGEMEEN",
        name="serietype",
    )
    serietype.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("comics", "serie_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_comics_id"), "comics", ["id"], unique=False)
    op.create_index(op.f("ix_comics_title"), "comics", ["title"], unique=False)
    op.add_column(
        "series",
        sa.Column("type", serietype, nullable=False, server_default="ALGEMEEN"),
    )
    op.create_index(op.f("ix_series_id"), "series", ["id"], unique=False)
    op.create_index(op.f("ix_series_title"), "series", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop the column before the type
    op.drop_index(op.f("ix_series_title"), table_name="series")
    op.drop_index(op.f("ix_series_id"), table_name="series")
    op.drop_column("series", "type")
    op.drop_index(op.f("ix_comics_title"), table_name="comics")
    op.drop_index(op.f("ix_comics_id"), table_name="comics")
    op.alter_column("comics", "serie_id", existing_type=sa.INTEGER(), nullable=True)

    # Drop the enum type
    serietype = sa.Enum(
        "KIDS",
        "COMIC",
        "GRAPHIC_NOVEL",
        "MANGA",
        "CARTOON",
        "VOLWASSENEN",
        "ALGEMEEN",
        name="serietype",
    )
    serietype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
